# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Set Python environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create symbolic links for python commands
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the .env file
COPY .env .

# Copy application files
COPY . .

# Expose API port
EXPOSE 8501

# Run the application
CMD ["sh", "-c", "cd /app && streamlit run main.py"]